### ISSUE TITLE
Bump mayor version of the library to 1.0.0

### ISSUE THREAD

**Issue by artberri** [gucong3000/postcss-markdown#30]
Hello,

In the latest update of the library (https://github.com/gucong3000/postcss-markdown/pull/29), a breaking change has been added because you have upgraded `remark` from 9.0.0 to 10.0.0. Now, this library (remark) is requiring Typescript >=3.0.0, and for this reason (and others) they bumped a new mayor version from 9 to 10. So, with this update, `postcss-markdown` is becoming also incompatible with Typescript < 3, which is used by a lot of users. 

I'm not sure why are you still using 0.X.X versions, I suppose you are still considering it a beta version, but your awesome library is being already used by others like [stylelint](https://github.com/stylelint), so in my opinion a good approach would be to start using 1.X.X version numbers and above in order to fit [semantic versioning](https://semver.org/) properly. I mean, upgrading the mayor version number when you introduce a breaking change or a mayor update of a direct dependency. 

What do you think?

**Comment by hudochenkov** [comment]
> I'm not sure why are you still using 0.X.X versions, I suppose you are still considering it a beta version, but your awesome library is being already used by others like stylelint, so in my opinion a good approach would be to start using 1.X.X version numbers and above in order to fit semantic versioning properly. I mean, upgrading the mayor version number when you introduce a breaking change or a mayor update of a direct dependency.

This library [follows](https://semver.org/#spec-item-4) semver. From what I see from a side, currently, every release of this library could have breaking changes. That's why @gucong3000 keeping it as 0.x for now, if I understand correctly.

**Comment by artberri** [comment]
You are right and my `in order to fit semantic versioning properly` sentence sounds a bit rude even it was not my intention, sorry about that. What I wanted to suggest is that, taking into account how much is this library used, it would be nice to start taking more control over breaking changes. Of course, it's up to @gucong3000 to decide and whatever he choose will be fine.

As I explained in the https://github.com/stylelint/stylelint/issues/3907 issue, the breaking change (if it exists) seems to not be caused by this library, so, I will close this issue also.

Thank you, both, for your contributions.

**Comment by gucong3000** [comment]
Thank you for your suggestion, I will consider upgrading to 1.x.x as soon as possible.
