### ISSUE TITLE
Why PostCSS

### ISSUE THREAD

**Issue by redaxmedia** [gucong3000/postcss-markdown#4]
Hello,

do I understand this correct that you are creating markdown here? So from my understanding, this should be a [PostHTML](https://github.com/posthtml/posthtml) plugin and not PostCSS?

**Comment by gucong3000** [comment]
The main use case of this plugin is apply PostCSS transformations to CSS (and CSS-like) code blocks in markdown file.

**Comment by gucong3000** [comment]
I'm sorry, the document hasn't been updated, and a new version will be released by this weekend.

**Comment by redaxmedia** [comment]
Then it should be a PostHTML plugin that is named markdown-css-autoprefix or something. It actually does not matter that you add CSS related content. What matters is that you are manipulating HTML like files and not CSS files.

Same for your other project here on GitHub that seems to be the base of this one.

This is just my opinion according to the separarion of concerns pattern.

**Comment by gucong3000** [comment]
It is is parser & stringifier for PostCSS to parsing __CSS code blocks__ in *.md, It is about `CSS`, not HTML.

**Comment by gucong3000** [comment]
It is not work for run time, It is work for static code lint and fix.

**Comment by redaxmedia** [comment]
Okay, thank you for the explanation.
